config:
  heading-increment: false
  lint-length: false

# Hide the Finding: <list of globs> when markdownlint fixes files
noProgress: true

# Hide the markdownlint-cli and markdownlint versions on each block
noBanner: true

# Ignore files referenced by .gitignore (only valid at root)
gitignore: true

# Define glob expressions to ignore
ignores:
  - "gp/chats/**" # Ignore gp chats

# Fix any fixable errors
fix: true
